ShopASPNet/Controllers/ItemsController.cs
using System.Runtime.InteropServices.JavaScript;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShopASPNet.Interfaces;
using ShopASPNet.Models.Items;
using ShopASPNet.Models.Requests;

namespace ShopASPNet.Controllers;

[Authorize]
[Controller]
[Route("[controller]")]
public class ItemsController : Controller {
    private readonly IItemRepository _itemRepository;
    
    public ItemsController(IItemRepository itemRepository) {
        _itemRepository = itemRepository;
    }
    
    [AllowAnonymous]
    [HttpGet]
    [Route("")]
    [Route(nameof(Index))]
    public async Task<IActionResult> Index() {
        var items = await _itemRepository.GetAllAsync();
        return View(items);
    }
    
    [AllowAnonymous]
    [HttpGet]
    [Route(nameof(Add))]
    public IActionResult Add() {
        return View();
    }
    
    [HttpPost]
    [Route(nameof(Add))]
    public async Task<IActionResult> Add(ItemRequest itemRequest) {
        var creationDate = DateTime.Now;
        
        var item = new Item {
            Name = itemRequest.Name,
            Description = itemRequest.Description,
            Price = itemRequest.Price,
            Created = creationDate,
            LastEdited = creationDate,
        };
        
        var result = await _itemRepository.AddAsync(item);
        
        if (result is false)
            return Forbid();
        return RedirectToAction("Index");
    }

    [HttpGet]
    [Route(nameof(Edit))]
    public async Task<IActionResult> Edit(int id) {
        var item = await _itemRepository.GetByIdAsync(id);
        return View(item);
    }

    [HttpPost]
    [Route(nameof(Edit))]
    public async Task<IActionResult> Edit(Item item) {
        item.LastEdited = DateTime.Now;
        await _itemRepository.UpdateAsync(item);
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    [Route(nameof(Delete))]
    public async Task<IActionResult> Delete(int id) {
        await _itemRepository.RemoveByIdAsync(id);
        return RedirectToAction("Index");
    }

    [AllowAnonymous]
    [HttpGet]
    [Route(nameof(Details))]
    public async Task<IActionResult> Details(int id) {
        var item = await _itemRepository.GetByIdAsync(id);
        return View(item);
    }
}

ShopASPNet/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopASPNet.Data;
using ShopASPNet.Models.Requests;

namespace ShopASPNet.Controllers; 

[Authorize]
public class ProfileController : Controller {
    private readonly ShopDbContext _context;
    
    public ProfileController(ShopDbContext context) {
        _context = context;
    }

    public async Task<IActionResult> Index() {
        var user = await _context.Users.FirstOrDefaultAsync(
            u => User.Identity != null && u.UserName == User.Identity.Name);
        if (user is null)
            return RedirectToAction("Error", "Home");
        
        return View(user);
    }

    [HttpGet]
    public async Task<IActionResult> Edit() {
        var user = await _context.Users.FirstOrDefaultAsync(
            u => User.Identity != null && u.UserName == User.Identity.Name);
        if (user is null)
            return RedirectToAction("Error", "Home");

        var request = new UserSignUpRequest {
            Username = user.UserName,
            FirstName = user.FirstName,
            LastName = user.LastName,
        };
        return View(request);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(UserSignUpRequest request) {
        var user = await _context.Users.FirstOrDefaultAsync(u => User.Identity != null && u.UserName == User.Identity.Name);
        if (user is null) {
            TempData["Error"] = "Something went wrong";
            return await Edit();
        }

        if (!_context.Users.Any(u => u.UserName == request.Username))
            user.UserName = request.Username;
        user.FirstName = request.FirstName;
        user.LastName = request.LastName;

        _context.Users.Update(user);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
    }
}

ShopASPNet/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopASPNet.Data;
using ShopASPNet.Interfaces;
using ShopASPNet.Models.Items;
using ShopASPNet.Models.Requests;
using ShopASPNet.Models.UserModels;

namespace ShopASPNet.Controllers; 

[Controller]
public class ShoppingCartController : Controller {
    private readonly UserManager<AppUser> _userManager;
    private readonly IShoppingCartRepository _shoppingCartRepository;
    private readonly ShopDbContext _context;
    
    public ShoppingCartController(UserManager<AppUser> userManager, IShoppingCartRepository shoppingCartRepository, ShopDbContext context) {
        _userManager = userManager;
        _shoppingCartRepository = shoppingCartRepository;
        _context = context;
    }

    [HttpGet]
    public async Task<IActionResult> Index() {
        var user = await _userManager.GetUserAsync(HttpContext.User);
        if (user is null)
            return Forbid();

        var userId = user.Id;
        var cart = await _shoppingCartRepository.GetCartByIdAsync(userId);

        return View(cart);
    }

    [HttpGet]
    public async Task<IActionResult> Add(int itemId) {
        var item = await _context.Items.FirstOrDefaultAsync(i => i.Id == itemId);
        if (item is null)
            return RedirectToAction("Index");
        
        var cartItem = new ItemToCartRequest {
            ItemId = itemId,
            Quantity = 1,
        };
        return View(cartItem);
    }

    [HttpPost]
    public async Task<IActionResult> Add(ItemToCartRequest request) {
        if (User.Identity?.Name != null)
            await _shoppingCartRepository.AddItemToCartAsync(User.Identity.Name, request.ItemId, request.Quantity);
        return RedirectToAction("Index");
    }
}

ShopASPNet/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopASPNet.Models.Requests;
using ShopASPNet.Models.UserModels;

namespace ShopASPNet.Controllers; 

public class UserController : Controller {
    private readonly SignInManager<AppUser> _signInManager;
    private readonly UserManager<AppUser> _userManager;
    
    public UserController(SignInManager<AppUser> signInManager, UserManager<AppUser> userManager) {
        _signInManager = signInManager;
        _userManager = userManager;
    }

    [HttpGet]
    public IActionResult LogIn(string? returnUrl = null) {
        TempData["ReturnUrl"] = returnUrl ?? Url.Content("~/");
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> LogIn(UserLogInRequest request) {
        var result = await _signInManager.PasswordSignInAsync(
            request.Username, request.Password, request.RememberMe, lockoutOnFailure: true);

        if (!result.Succeeded) {
            TempData["Error"] = "Something went wrong";
            return View();
        }

        if (TempData["ReturnUrl"] is string returnUrl)
            return LocalRedirect(returnUrl);
        return RedirectToAction("Index", "Home");
    }

    [HttpGet]
    public IActionResult SignUp() {
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> SignUp(UserSignUpRequest request) {
        if (!ModelState.IsValid) {
            TempData["Error"] = "Something went wrong.";
            return View();
        }

        var user = new AppUser {
            UserName = request.Username,
            FirstName = request.FirstName,
            LastName = request.LastName,
        };
        
        var result = await _userManager.CreateAsync(user, request.Password);
        if (!result.Succeeded) {
            TempData["Error"] = "Something went wrong";
            return View();
        }

        var logInRequest = new UserLogInRequest {
            Username = user.UserName,
            Password = request.Password,
        };
        return await LogIn(logInRequest);
    }

    public async Task<IActionResult> LogOut() {
        await _signInManager.SignOutAsync();
        return RedirectToAction("Index", "Home");
    }
}

ShopASPNet/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using ShopASPNet.Models.UserModels

@inject SignInManager<AppUser> SignInManager 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ShopASPNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ShopASPNet.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShopASPNet</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">Items</a>
                    </li>
                </ul>
                
                @if (!SignInManager.IsSignedIn(User)) {
                    <ul class="navbar-nav flex-grow-2">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LogIn">Log in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignUp">Sign up</a>
                        </li>
                    </ul>
                }
                else {
                    <ul class="navbar-nav flex-grow-2">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Cart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LogOut">Log out</a>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - ShopASPNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>